package com.tencent.mm.compatible.d;

import com.tencent.mm.sdk.platformtools.w;

public final class j {
    public int gPK = -1;
    public int gPL = -1;
    public int gPM = -1;
    public int gPN = -1;
    public int gPO = -1;
    public int gPP = -1;
    public int gPQ = -1;
    public int gPR = -1;
    public boolean gPS = false;
    public int gPT = -1;
    public int gPU = -1;
    public int gPV = -1;
    public int gPW = -1;
    public int gPX = -1;
    public int gPY = -1;
    public int gPZ = -1;
    public String gQA = null;
    public String gQB = null;
    public String gQC = null;
    public String gQD = null;
    public int gQE = -1;
    public int gQF = 2;
    public int gQG = 1;
    public int gQH = 1;
    public int gQI = -1;
    public int gQa = -1;
    public int gQb = -1;
    public int gQc = -1;
    public int gQd = -1;
    public int gQe = -1;
    public int gQf = -1;
    public int gQg = -1;
    public int gQh = -1;
    public int gQi = -1;
    public int gQj = -1;
    public int gQk = -1;
    public int gQl = -1;
    public double gQm = -1.0d;
    public int gQn = -1;
    public int gQo = -1;
    public int gQp = -1;
    public int gQq = -1;
    public String gQr = null;
    public String gQs = null;
    public String gQt = null;
    public String gQu = null;
    public String gQv = null;
    public String gQw = null;
    public String gQx = null;
    public String gQy = null;
    public String gQz = null;

    public j() {
        reset();
    }

    public final void reset() {
        this.gPK = -1;
        this.gPL = -1;
        this.gPM = -1;
        this.gPN = -1;
        this.gPO = -1;
        this.gPP = -1;
        this.gPR = -1;
        this.gPQ = -1;
        this.gPU = -1;
        this.gPV = -1;
        this.gPW = -1;
        this.gPX = -1;
        this.gPS = false;
        this.gPT = -1;
        this.gPY = -1;
        this.gPZ = -1;
        this.gQa = -1;
        this.gQb = -1;
        this.gQc = -1;
        this.gQf = -1;
        this.gQe = -1;
        this.gQg = -1;
        this.gQh = -1;
        this.gQd = -1;
        this.gQg = -1;
        this.gQh = -1;
        this.gQk = -1;
        this.gQn = -1;
        this.gQo = -1;
        this.gQp = -1;
        this.gQq = -1;
        this.gQr = null;
        this.gQs = null;
        this.gQt = null;
        this.gQu = null;
        this.gQi = -1;
        this.gQv = null;
        this.gQw = null;
        this.gQx = null;
        this.gQy = null;
        this.gQz = null;
        this.gQA = null;
        this.gQj = -1;
        this.gQB = null;
        this.gQC = null;
        this.gQD = null;
        this.gQE = -1;
        this.gQF = 2;
        this.gQG = 1;
        this.gQH = 1;
        this.gQl = -1;
    }

    public final void dump() {
        w.d("MicroMsg.CommonInfo", "js " + this.gPK);
        w.d("MicroMsg.CommonInfo", "stopBluetoothInBR " + this.gPL);
        w.d("MicroMsg.CommonInfo", "stopBluetoothInBU " + this.gPM);
        w.d("MicroMsg.CommonInfo", "setBluetoothScoOn " + this.gPO);
        w.d("MicroMsg.CommonInfo", "startBluetoothSco " + this.gPN);
        w.d("MicroMsg.CommonInfo", "voiceSearchFastMode " + this.gPP);
        w.d("MicroMsg.CommonInfo", "pcmReadMode " + this.gPR);
        w.d("MicroMsg.CommonInfo", "pcmBufferRate " + this.gPQ);
        w.d("MicroMsg.CommonInfo", "audioPrePro " + this.gPU);
        w.d("MicroMsg.CommonInfo", "voicemsgfd " + this.gPV);
        w.d("MicroMsg.CommonInfo", "htcvoicemode " + this.gPW);
        w.d("MicroMsg.CommonInfo", "samsungvoicemode " + this.gPX);
        w.d("MicroMsg.CommonInfo", "speexBufferRate " + this.gPY);
        w.d("MicroMsg.CommonInfo", "linespe " + this.gPZ);
        w.d("MicroMsg.CommonInfo", "fixspan " + this.gQk);
        w.d("MicroMsg.CommonInfo", "extvideo " + this.gQa);
        w.d("MicroMsg.CommonInfo", "extvideosam " + this.gQb);
        w.d("MicroMsg.CommonInfo", "sysvideodegree " + this.gQc);
        w.d("MicroMsg.CommonInfo", "mmnotify " + this.gQf);
        w.d("MicroMsg.CommonInfo", "extsharevcard " + this.gQe);
        w.d("MicroMsg.CommonInfo", "audioformat " + this.gQg);
        w.d("MicroMsg.CommonInfo", "qrcam " + this.gQh);
        w.d("MicroMsg.CommonInfo", "mBase " + this.gQr);
        w.d("MicroMsg.CommonInfo", "mPackageInfo " + this.gQs);
        w.d("MicroMsg.CommonInfo", "mClassLoader " + this.gQt);
        w.d("MicroMsg.CommonInfo", "mResources " + this.gQu);
        w.d("MicroMsg.CommonInfo", "sysvideofp " + this.gQi);
        w.d("MicroMsg.CommonInfo", "extstoragedir " + this.gQv);
        w.d("MicroMsg.CommonInfo", "extpubdir " + this.gQw);
        w.d("MicroMsg.CommonInfo", "extdatadir " + this.gQx);
        w.d("MicroMsg.CommonInfo", "extrootdir " + this.gQy);
        w.d("MicroMsg.CommonInfo", "extstoragestate " + this.gQz);
        w.d("MicroMsg.CommonInfo", "extcachedir " + this.gQA);
        w.d("MicroMsg.CommonInfo", "extvideoplayer " + this.gQj);
        w.d("MicroMsg.CommonInfo", "loadDrawable " + this.gQB);
        w.d("MicroMsg.CommonInfo", "loadXmlResourceParser " + this.gQC);
        w.d("MicroMsg.CommonInfo", "voipAudioPrePro " + this.gQn);
        w.d("MicroMsg.CommonInfo", "voipAudioPreProNS " + this.gQo);
        w.d("MicroMsg.CommonInfo", "voipAudioPreProAEC " + this.gQp);
        w.d("MicroMsg.CommonInfo", "voipAudioPreProAGC " + this.gQq);
        w.d("MicroMsg.CommonInfo", "sight full screen type " + this.gQD);
        w.d("MicroMsg.CommonInfo", "checkSightDraftMd5 " + this.gQF);
        w.d("MicroMsg.CommonInfo", "swipeBackConfig " + this.gQG);
        w.d("MicroMsg.CommonInfo", "qrCodeZoom " + this.gQl);
    }
}
