package com.tencent.mm.plugin.sns.ui;

import com.tencent.mm.plugin.sns.data.d;
import com.tencent.mm.plugin.sns.storage.m;
import com.tencent.mm.protocal.c.ali;
import com.tencent.mm.protocal.c.bbk;
import com.tencent.mm.protocal.c.bfc;
import com.tencent.mm.vending.d.b;
import com.tencent.mm.vending.j.a;

public final class ax {
    public int afo;
    public String iQO;
    public String jia;
    public bbk pyI;
    public m pyJ;
    public bfc pyN;
    public String qIA;
    public String qIB;
    public boolean qIC;
    public boolean qID;
    public boolean qIE;
    public int qIF;
    public boolean qIG;
    public String qIH;
    public boolean qII;
    public boolean qIJ;
    public boolean qIK;
    public boolean qIL;
    public String qIM;
    public String qIN;
    public boolean qIO;
    public boolean qIP;
    public int qIQ;
    public boolean qIR;
    public boolean qIS;
    public String qIT;
    public boolean qIU;
    public boolean qIV;
    public int qIW;
    public double qIX;
    public b<a> qIY;
    public b<a> qIZ;
    public d qIj;
    public CharSequence qIk = null;
    public com.tencent.mm.j.a qIl;
    public String qIm;
    public long qIn;
    public String qIo;
    public int qIp;
    public int qIq;
    public int qIr;
    public boolean qIs;
    public String qIt;
    public String qIu;
    public com.tencent.mm.plugin.sns.storage.a qIv;
    public com.tencent.mm.plugin.sns.storage.b qIw;
    public String qIx;
    public String qIy;
    public String qIz;
    public b<a> qJa;
    public boolean qJb;
    public String qJc;
    public ali qJd;
    public boolean qpL;
    public String qtl;
}
