package com.tencent.mm.storage.a;

import com.tencent.mm.e.b.an;
import com.tencent.mm.protocal.c.pn;
import com.tencent.tmassistantsdk.downloadservice.DownloadInfo;
import com.tencent.tmassistantsdk.storage.table.DownloadSettingTable.Columns;
import java.lang.reflect.Field;

public final class a extends an {
    public static int TYPE_CUSTOM = 3;
    public static int TYPE_SYSTEM = 1;
    protected static com.tencent.mm.sdk.e.c.a gTP;
    public static int uKN = 2;
    public static int uKO = 4;
    public static int uKP = 256;
    public static int uKQ = 17;
    public static int uKR = 18;
    public static int uKS = 81;
    public static int uKT = 65;

    static {
        com.tencent.mm.sdk.e.c.a aVar = new com.tencent.mm.sdk.e.c.a();
        aVar.hXH = new Field[29];
        aVar.columns = new String[30];
        StringBuilder stringBuilder = new StringBuilder();
        aVar.columns[0] = "productID";
        aVar.uxd.put("productID", "TEXT PRIMARY KEY  COLLATE NOCASE ");
        stringBuilder.append(" productID TEXT PRIMARY KEY  COLLATE NOCASE ");
        stringBuilder.append(", ");
        aVar.uxc = "productID";
        aVar.columns[1] = "packIconUrl";
        aVar.uxd.put("packIconUrl", "TEXT");
        stringBuilder.append(" packIconUrl TEXT");
        stringBuilder.append(", ");
        aVar.columns[2] = "packGrayIconUrl";
        aVar.uxd.put("packGrayIconUrl", "TEXT");
        stringBuilder.append(" packGrayIconUrl TEXT");
        stringBuilder.append(", ");
        aVar.columns[3] = "packCoverUrl";
        aVar.uxd.put("packCoverUrl", "TEXT");
        stringBuilder.append(" packCoverUrl TEXT");
        stringBuilder.append(", ");
        aVar.columns[4] = "packName";
        aVar.uxd.put("packName", "TEXT");
        stringBuilder.append(" packName TEXT");
        stringBuilder.append(", ");
        aVar.columns[5] = "packDesc";
        aVar.uxd.put("packDesc", "TEXT");
        stringBuilder.append(" packDesc TEXT");
        stringBuilder.append(", ");
        aVar.columns[6] = "packAuthInfo";
        aVar.uxd.put("packAuthInfo", "TEXT");
        stringBuilder.append(" packAuthInfo TEXT");
        stringBuilder.append(", ");
        aVar.columns[7] = "packPrice";
        aVar.uxd.put("packPrice", "TEXT");
        stringBuilder.append(" packPrice TEXT");
        stringBuilder.append(", ");
        aVar.columns[8] = "packType";
        aVar.uxd.put("packType", "INTEGER");
        stringBuilder.append(" packType INTEGER");
        stringBuilder.append(", ");
        aVar.columns[9] = "packFlag";
        aVar.uxd.put("packFlag", "INTEGER");
        stringBuilder.append(" packFlag INTEGER");
        stringBuilder.append(", ");
        aVar.columns[10] = "packExpire";
        aVar.uxd.put("packExpire", "LONG");
        stringBuilder.append(" packExpire LONG");
        stringBuilder.append(", ");
        aVar.columns[11] = "packTimeStamp";
        aVar.uxd.put("packTimeStamp", "LONG");
        stringBuilder.append(" packTimeStamp LONG");
        stringBuilder.append(", ");
        aVar.columns[12] = "packCopyright";
        aVar.uxd.put("packCopyright", "TEXT");
        stringBuilder.append(" packCopyright TEXT");
        stringBuilder.append(", ");
        aVar.columns[13] = Columns.TYPE;
        aVar.uxd.put(Columns.TYPE, "INTEGER");
        stringBuilder.append(" type INTEGER");
        stringBuilder.append(", ");
        aVar.columns[14] = DownloadInfo.STATUS;
        aVar.uxd.put(DownloadInfo.STATUS, "INTEGER");
        stringBuilder.append(" status INTEGER");
        stringBuilder.append(", ");
        aVar.columns[15] = "sort";
        aVar.uxd.put("sort", "INTEGER default '1' ");
        stringBuilder.append(" sort INTEGER default '1' ");
        stringBuilder.append(", ");
        aVar.columns[16] = "lastUseTime";
        aVar.uxd.put("lastUseTime", "LONG");
        stringBuilder.append(" lastUseTime LONG");
        stringBuilder.append(", ");
        aVar.columns[17] = "packStatus";
        aVar.uxd.put("packStatus", "INTEGER default '0' ");
        stringBuilder.append(" packStatus INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[18] = "flag";
        aVar.uxd.put("flag", "INTEGER default '0' ");
        stringBuilder.append(" flag INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[19] = "recommand";
        aVar.uxd.put("recommand", "INTEGER default '0' ");
        stringBuilder.append(" recommand INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[20] = "sync";
        aVar.uxd.put("sync", "INTEGER default '0' ");
        stringBuilder.append(" sync INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[21] = "idx";
        aVar.uxd.put("idx", "INTEGER default '0' ");
        stringBuilder.append(" idx INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[22] = "BigIconUrl";
        aVar.uxd.put("BigIconUrl", "TEXT");
        stringBuilder.append(" BigIconUrl TEXT");
        stringBuilder.append(", ");
        aVar.columns[23] = "MutiLanName";
        aVar.uxd.put("MutiLanName", "TEXT");
        stringBuilder.append(" MutiLanName TEXT");
        stringBuilder.append(", ");
        aVar.columns[24] = "recommandType";
        aVar.uxd.put("recommandType", "INTEGER default '-1' ");
        stringBuilder.append(" recommandType INTEGER default '-1' ");
        stringBuilder.append(", ");
        aVar.columns[25] = "lang";
        aVar.uxd.put("lang", "TEXT");
        stringBuilder.append(" lang TEXT");
        stringBuilder.append(", ");
        aVar.columns[26] = "recommandWord";
        aVar.uxd.put("recommandWord", "TEXT");
        stringBuilder.append(" recommandWord TEXT");
        stringBuilder.append(", ");
        aVar.columns[27] = "buttonType";
        aVar.uxd.put("buttonType", "INTEGER");
        stringBuilder.append(" buttonType INTEGER");
        stringBuilder.append(", ");
        aVar.columns[28] = "count";
        aVar.uxd.put("count", "INTEGER");
        stringBuilder.append(" count INTEGER");
        aVar.columns[29] = "rowid";
        aVar.uxe = stringBuilder.toString();
        gTP = aVar;
    }

    protected final com.tencent.mm.sdk.e.c.a sY() {
        return gTP;
    }

    public final pn bMX() {
        pn pnVar = new pn();
        pnVar.tgW = this.field_productID;
        pnVar.muU = this.field_packIconUrl;
        pnVar.tuV = this.field_packName;
        pnVar.tuW = this.field_packDesc;
        pnVar.tuX = this.field_packAuthInfo;
        pnVar.tuY = this.field_packPrice;
        pnVar.tuZ = this.field_packType;
        pnVar.tva = this.field_packFlag;
        pnVar.tvd = this.field_packCoverUrl;
        pnVar.tve = (int) this.field_packExpire;
        pnVar.tvf = this.field_packCopyright;
        pnVar.tvD = (int) this.field_packTimeStamp;
        pnVar.tvg = this.field_packPrice;
        return pnVar;
    }

    public final String toString() {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("field_productID:").append(this.field_productID).append("\n");
        stringBuilder.append("field_packIconUrl:").append(this.field_packIconUrl).append("\n");
        stringBuilder.append("field_packGrayIconUrl:").append(this.field_packGrayIconUrl).append("\n");
        stringBuilder.append("field_packCoverUrl:").append(this.field_packCoverUrl).append("\n");
        stringBuilder.append("field_packName:").append(this.field_packName).append("\n");
        stringBuilder.append("field_packDesc:").append(this.field_packDesc).append("\n");
        stringBuilder.append("field_packAuthInfo:").append(this.field_packAuthInfo).append("\n");
        stringBuilder.append("field_packPrice:").append(this.field_packPrice).append("\n");
        stringBuilder.append("field_packType:").append(this.field_packType).append("\n");
        stringBuilder.append("field_packFlag:").append(this.field_packFlag).append("\n");
        stringBuilder.append("field_packExpire:").append(this.field_packExpire).append("\n");
        stringBuilder.append("field_packTimeStamp:").append(this.field_packTimeStamp).append("\n");
        stringBuilder.append("field_packCopyright:").append(this.field_packCopyright).append("\n");
        stringBuilder.append("field_type:").append(this.field_type).append("\n");
        stringBuilder.append("field_status:").append(this.field_status).append("\n");
        stringBuilder.append("field_sort:").append(this.field_sort).append("\n");
        stringBuilder.append("field_lastUseTime:").append(this.field_lastUseTime).append("\n");
        stringBuilder.append("field_packStatus:").append(this.field_packStatus).append("\n");
        stringBuilder.append("field_recommand:").append(this.field_recommand).append("\n");
        stringBuilder.append("field_sync:").append(this.field_sync).append("\n");
        stringBuilder.append("field_idx:").append(this.field_idx).append("\n");
        stringBuilder.append("field_BigIconUrl:").append(this.field_BigIconUrl).append("\n");
        stringBuilder.append("field_MutiLanName:").append(this.field_MutiLanName).append("\n");
        stringBuilder.append("field_count:").append(this.field_count).append("\n");
        return stringBuilder.toString();
    }
}
